services:
  mexc-bot-2:
    build: .
    container_name: mexc-futures-bot-2
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./mexc_futures_bot.py:/app/mexc_futures_bot.py:ro
      - ./bot_data.pkl:/app/bot_data.pkl
    dns:
      - 8.8.8.8
      - 8.8.4.4
